### ISSUE TITLE
the goquery string doesn't work. 

### ISSUE THREAD

**Issue by JizongL** [blackhat-go/bhg#17]
The book suggests the following 
```
s := "html body div#b_content ol#b_results li.b_algo div.b_title h2"
```
but in reality, it doesn't work. I have attempted to make small changes to debug but I didn't get any luck. 

I assume the logic is to loop through every one of these tag from s, then attempt to find if a with attr href exist, if it does then save it, if it doesn't, then return. However, the loop dies when it reaches div#b_content, although the html elements of that page from bing does have a div tag with id b_content. Please give some advice how to fix this. thanks.

**Comment by tomsteele** [comment]
@JizongL see this PR https://github.com/blackhat-go/bhg/pull/13
