### ISSUE TITLE
Chapter 3 bing-metadata

### ISSUE THREAD

**Issue by smilnovi** [blackhat-go/bhg#18]
Hi,

It seems bing no longer accepts requests without proper user-agent header, if it doesn't recognize the user agent, it returns "no results found" even if the URL generated returns results if used in a browser. I had to modify the main.go to use http.NewRequest instead, like this (it seems gitlab formatting messes up the code):

`client := &http.Client{}
    q := fmt.Sprintf(
        "site:%s && filetype:%s && instreamset:(url title):%s",
        domain,
        filetype,
        filetype)

    search := fmt.Sprintf("http://www.bing.com/search?q=%s", url.QueryEscape(q))
    req, err := http.NewRequest("GET", search, nil)
    if err != nil {
        return
    }

    req.Header.Add("user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36")
    resp, err := client.Do(req)
    if err != nil {
        return
    }

    doc, err := goquery.NewDocumentFromReader(resp.Body)`

**Comment by tomsteele** [comment]
Nice job, way to improvise :)
