### ISSUE TITLE
Error get smb package on chapter 6

### ISSUE THREAD

**Issue by hung1024** [blackhat-go/bhg#19]
I bought the book on amazon, currently I am reading chapter 6, SMB and get this error "epository not found".
I am using visual studio code, I have no problem with "**go get**" of other library but this smb package.
Please help.

PS E:\Go Pen> go get github.com/bhg/ch-6/smb/smb
# cd .; git clone -- https://github.com/bhg/ch-6 C:\Users\PC\go\src\github.com\bhg\ch-6
Cloning into 'C:\Users\PC\go\src\github.com\bhg\ch-6'...
Logon failed, use ctrl+c to cancel basic credential prompt.
remote: Repository not found.
fatal: repository 'https://github.com/bhg/ch-6/' not found
package github.com/bhg/ch-6/smb/smb: exit status 128

**Comment by tomsteele** [comment]
Try changing the path to `go get github.com/blackhat-go/bhg/ch-6/smb/smb`
