### ISSUE TITLE
Erreta: Chp 2 pp 36

### ISSUE THREAD

**Issue by robertsimoes** [blackhat-go/bhg#3]
:wave:

Making my way through Black Hat Go print release. 

Noticed one small point of error between code here and in the book so far. 

pp. 35 maps to [ch-2/echo-server#L4](https://github.com/blackhat-go/bhg/blob/master/ch-2/echo-server/main.go#L4) but unfortunately is missing `io` import compared to the code :(

The book only reads
```
import (
    "log"
    "net"
)
```

**Comment by dreddsa5dies** [comment]
And there is

**Comment by tomsteele** [comment]
Good catch @robertsimoes, I'll get this over to NoStarch :)
