### ISSUE TITLE
Comment mismatch with code

### ISSUE THREAD

**Issue by brandentimm** [blackhat-go/bhg#7]
https://github.com/blackhat-go/bhg/blob/bcc5ee22198b3af7aa536d4f34b372116103a89e/ch-2/netcat-exec/main.go#L17

Given the comment on line 15, it seems that arguments to Command should be "/bin/sh", "-i"  instead of "cmd.exe".

**Comment by tomsteele** [comment]
Probs

**Comment by tomsteele** [comment]
Fixed
